/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`messaging_custom_message`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessagingCustomMessageError {
    Status501(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`messaging_push_update`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessagingPushUpdateError {
    Status501(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`messaging_push_user_update`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessagingPushUserUpdateError {
    Status501(),
    UnknownValue(serde_json::Value),
}


/// Send a custom message via the messaging service.
pub async fn messaging_custom_message(configuration: &configuration::Configuration, custom_message: Option<models::CustomMessage>) -> Result<(), Error<MessagingCustomMessageError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_custom_message = custom_message;

    let uri_str = format!("{}/messaging/custom", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_custom_message);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<MessagingCustomMessageError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Push an update via the messaging service.
pub async fn messaging_push_update(configuration: &configuration::Configuration, ) -> Result<(), Error<MessagingPushUpdateError>> {

    let uri_str = format!("{}/messaging/update", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<MessagingPushUpdateError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Push a user update via the messaging service.
pub async fn messaging_push_user_update(configuration: &configuration::Configuration, unique_id: &str) -> Result<(), Error<MessagingPushUserUpdateError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_unique_id = unique_id;

    let uri_str = format!("{}/messaging/update/{uniqueId}", configuration.base_path, uniqueId=crate::apis::urlencode(p_path_unique_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<MessagingPushUserUpdateError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

