/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionSource : Who performed the action
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionSource {
    /// A player unique id (UUID)
    #[serde(rename = "uniqueId")]
    pub unique_id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
}

impl ActionSource {
    /// Who performed the action
    pub fn new(unique_id: uuid::Uuid, name: String) -> ActionSource {
        ActionSource { unique_id, name }
    }
}
