/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionTarget : Who/what was the action performed on
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionTarget {
    /// A player unique id (UUID)
    #[serde(rename = "uniqueId", skip_serializing_if = "Option::is_none")]
    pub unique_id: Option<uuid::Uuid>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ActionTarget {
    /// Who/what was the action performed on
    pub fn new(name: String, r#type: Type) -> ActionTarget {
        ActionTarget {
            unique_id: None,
            name,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "group")]
    Group,
    #[serde(rename = "track")]
    Track,
}

impl Default for Type {
    fn default() -> Type {
        Self::User
    }
}

