/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Action :
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Action {
    /// The time when the action happened, defaults to the current time
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i32>,
    #[serde(rename = "source")]
    pub source: Box<models::ActionSource>,
    #[serde(rename = "target")]
    pub target: Box<models::ActionTarget>,
    /// A description of the action
    #[serde(rename = "description")]
    pub description: String,
}

impl Action {
    ///
    pub fn new(
        source: models::ActionSource,
        target: models::ActionTarget,
        description: String,
    ) -> Action {
        Action {
            timestamp: None,
            source: Box::new(source),
            target: Box::new(target),
            description,
        }
    }
}
