/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Context : A context pair.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Context {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl Context {
    /// A context pair.
    pub fn new(key: String, value: String) -> Context {
        Context {
            key,
            value,
        }
    }
}

