/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomMessageReceiveEvent : Called when a custom payload message is received via the messaging service
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomMessageReceiveEvent {
    #[serde(rename = "channelId")]
    pub channel_id: String,
    #[serde(rename = "payload")]
    pub payload: String,
}

impl CustomMessageReceiveEvent {
    /// Called when a custom payload message is received via the messaging service
    pub fn new(channel_id: String, payload: String) -> CustomMessageReceiveEvent {
        CustomMessageReceiveEvent {
            channel_id,
            payload,
        }
    }
}

