/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomMessage : A custom message to send via the messaging service
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomMessage {
    #[serde(rename = "channelId")]
    pub channel_id: String,
    #[serde(rename = "payload")]
    pub payload: String,
}

impl CustomMessage {
    /// A custom message to send via the messaging service
    pub fn new(channel_id: String, payload: String) -> CustomMessage {
        CustomMessage {
            channel_id,
            payload,
        }
    }
}
