/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetActions200Response {
    #[serde(rename = "entries", skip_serializing_if = "Option::is_none")]
    pub entries: Option<Vec<models::Action>>,
    #[serde(rename = "overallSize", skip_serializing_if = "Option::is_none")]
    pub overall_size: Option<i32>,
}

impl GetActions200Response {
    pub fn new() -> GetActions200Response {
        GetActions200Response {
            entries: None,
            overall_size: None,
        }
    }
}
