/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetEventPreSync200ResponseInner {
    #[serde(rename = "event")]
    pub event: Event,
    /// Called just before a full synchronisation task runs
    #[serde(rename = "data")]
    pub data: serde_json::Value,
}

impl GetEventPreSync200ResponseInner {
    pub fn new(event: Event, data: serde_json::Value) -> GetEventPreSync200ResponseInner {
        GetEventPreSync200ResponseInner {
            event,
            data,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "message")]
    Message,
}

impl Default for Event {
    fn default() -> Event {
        Self::Message
    }
}

