/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Group {
    /// A group name
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
    /// A map (array) of nodes.
    #[serde(rename = "nodes")]
    pub nodes: Vec<models::Node>,
    #[serde(rename = "metadata")]
    pub metadata: Box<models::Metadata>,
}

impl Group {
    pub fn new(name: String, nodes: Vec<models::Node>, metadata: models::Metadata) -> Group {
        Group {
            name,
            display_name: None,
            weight: None,
            nodes,
            metadata: Box::new(metadata),
        }
    }
}

