/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Health : The health status of the app
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Health {
    /// if the app is healthy
    #[serde(rename = "health")]
    pub health: bool,
    /// extra information about the healthcheck result
    #[serde(rename = "details")]
    pub details: serde_json::Value,
}

impl Health {
    /// The health status of the app
    pub fn new(health: bool, details: serde_json::Value) -> Health {
        Health {
            health,
            details,
        }
    }
}

