/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LogBroadcastEventOrigin : Represents where a log entry is from
/// Represents where a log entry is from
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LogBroadcastEventOrigin {
    #[serde(rename = "local")]
    Local,
    #[serde(rename = "local_api")]
    LocalApi,
    #[serde(rename = "remote")]
    Remote,
}

impl std::fmt::Display for LogBroadcastEventOrigin {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Local => write!(f, "local"),
            Self::LocalApi => write!(f, "local_api"),
            Self::Remote => write!(f, "remote"),
        }
    }
}

impl Default for LogBroadcastEventOrigin {
    fn default() -> LogBroadcastEventOrigin {
        Self::Local
    }
}
