/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LogBroadcastEvent : Called when a log entry is about to be sent to notifiable players on the platform
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogBroadcastEvent {
    #[serde(rename = "entry")]
    pub entry: Box<models::Action>,
    #[serde(rename = "origin")]
    pub origin: models::LogBroadcastEventOrigin,
}

impl LogBroadcastEvent {
    /// Called when a log entry is about to be sent to notifiable players on the platform
    pub fn new(entry: models::Action, origin: models::LogBroadcastEventOrigin) -> LogBroadcastEvent {
        LogBroadcastEvent {
            entry: Box::new(entry),
            origin,
        }
    }
}

