/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Metadata : Metadata about a user or group.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Metadata {
    #[serde(rename = "meta")]
    pub meta: serde_json::Value,
    #[serde(rename = "prefix", skip_serializing_if = "Option::is_none")]
    pub prefix: Option<String>,
    #[serde(rename = "suffix", skip_serializing_if = "Option::is_none")]
    pub suffix: Option<String>,
    #[serde(rename = "primaryGroup", skip_serializing_if = "Option::is_none")]
    pub primary_group: Option<String>,
}

impl Metadata {
    /// Metadata about a user or group.
    pub fn new(meta: serde_json::Value) -> Metadata {
        Metadata {
            meta,
            prefix: None,
            suffix: None,
            primary_group: None,
        }
    }
}

