/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewUser {
    /// A player unique id (UUID)
    #[serde(rename = "uniqueId")]
    pub unique_id: uuid::Uuid,
    #[serde(rename = "username")]
    pub username: String,
}

impl NewUser {
    pub fn new(unique_id: uuid::Uuid, username: String) -> NewUser {
        NewUser {
            unique_id,
            username,
        }
    }
}

