/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NewNode : Represents a LuckPerms \"node\".  Nodes encapsulate more than just permission assignments. Nodes are used to store data about inherited groups, as well as assigned prefixes, suffixes and meta values.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewNode {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<bool>,
    /// A set of context pairs.
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<Vec<models::Context>>,
    /// The instant the node will expire, in epoch seconds.
    #[serde(rename = "expiry", skip_serializing_if = "Option::is_none")]
    pub expiry: Option<i32>,
}

impl NewNode {
    /// Represents a LuckPerms \"node\".  Nodes encapsulate more than just permission assignments. Nodes are used to store data about inherited groups, as well as assigned prefixes, suffixes and meta values.
    pub fn new(key: String) -> NewNode {
        NewNode {
            key,
            value: None,
            context: None,
            expiry: None,
        }
    }
}

