/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Node : Represents a LuckPerms \"node\".  Nodes encapsulate more than just permission assignments. Nodes are used to store data about inherited groups, as well as assigned prefixes, suffixes and meta values.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Node {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "value")]
    pub value: bool,
    /// A set of context pairs.
    #[serde(rename = "context")]
    pub context: Vec<models::Context>,
    /// The instant the node will expire, in epoch seconds.
    #[serde(rename = "expiry", skip_serializing_if = "Option::is_none")]
    pub expiry: Option<i32>,
}

impl Node {
    /// Represents a LuckPerms \"node\".  Nodes encapsulate more than just permission assignments. Nodes are used to store data about inherited groups, as well as assigned prefixes, suffixes and meta values.
    pub fn new(key: String, r#type: Type, value: bool, context: Vec<models::Context>) -> Node {
        Node {
            key,
            r#type,
            value,
            context,
            expiry: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "permission")]
    Permission,
    #[serde(rename = "regex_permission")]
    RegexPermission,
    #[serde(rename = "inheritance")]
    Inheritance,
    #[serde(rename = "prefix")]
    Prefix,
    #[serde(rename = "suffix")]
    Suffix,
    #[serde(rename = "meta")]
    Meta,
    #[serde(rename = "weight")]
    Weight,
    #[serde(rename = "display_name")]
    DisplayName,
}

impl Default for Type {
    fn default() -> Type {
        Self::Permission
    }
}
