/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PermissionCheckRequest : The request parameters for a permission check.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PermissionCheckRequest {
    /// The permission to check for
    #[serde(rename = "permission")]
    pub permission: String,
    #[serde(rename = "queryOptions", skip_serializing_if = "Option::is_none")]
    pub query_options: Option<Box<models::QueryOptions>>,
}

impl PermissionCheckRequest {
    /// The request parameters for a permission check.
    pub fn new(permission: String) -> PermissionCheckRequest {
        PermissionCheckRequest {
            permission,
            query_options: None,
        }
    }
}

