/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostNetworkSyncEvent : Called after a network synchronisation task has been completed
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostNetworkSyncEvent {
    /// A player unique id (UUID)
    #[serde(rename = "syncId")]
    pub sync_id: uuid::Uuid,
    #[serde(rename = "type")]
    pub r#type: models::SyncType,
    #[serde(rename = "didSyncOccur")]
    pub did_sync_occur: bool,
    /// A player unique id (UUID)
    #[serde(
        rename = "specificUserUniqueId",
        skip_serializing_if = "Option::is_none"
    )]
    pub specific_user_unique_id: Option<uuid::Uuid>,
}

impl PostNetworkSyncEvent {
    /// Called after a network synchronisation task has been completed
    pub fn new(
        sync_id: uuid::Uuid,
        r#type: models::SyncType,
        did_sync_occur: bool,
    ) -> PostNetworkSyncEvent {
        PostNetworkSyncEvent {
            sync_id,
            r#type,
            did_sync_occur,
            specific_user_unique_id: None,
        }
    }
}
