/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PreNetworkSyncEvent : Called after a request for synchronisation has been received via the messaging service, but before it has actually been completed
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PreNetworkSyncEvent {
    /// A player unique id (UUID)
    #[serde(rename = "syncId")]
    pub sync_id: uuid::Uuid,
    #[serde(rename = "type")]
    pub r#type: models::SyncType,
    /// A player unique id (UUID)
    #[serde(rename = "specificUserUniqueId", skip_serializing_if = "Option::is_none")]
    pub specific_user_unique_id: Option<uuid::Uuid>,
}

impl PreNetworkSyncEvent {
    /// Called after a request for synchronisation has been received via the messaging service, but before it has actually been completed
    pub fn new(sync_id: uuid::Uuid, r#type: models::SyncType) -> PreNetworkSyncEvent {
        PreNetworkSyncEvent {
            sync_id,
            r#type,
            specific_user_unique_id: None,
        }
    }
}

