/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryOptions {
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<Mode>,
    #[serde(rename = "flags", skip_serializing_if = "Option::is_none")]
    pub flags: Option<Vec<Flags>>,
    /// A set of context pairs.
    #[serde(rename = "contexts", skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<models::Context>>,
}

impl QueryOptions {
    pub fn new() -> QueryOptions {
        QueryOptions {
            mode: None,
            flags: None,
            contexts: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "contextual")]
    Contextual,
    #[serde(rename = "non_contextual")]
    NonContextual,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Contextual
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Flags {
    #[serde(rename = "resolve_inheritance")]
    ResolveInheritance,
    #[serde(rename = "include_nodes_without_server_context")]
    IncludeNodesWithoutServerContext,
    #[serde(rename = "include_nodes_without_world_context")]
    IncludeNodesWithoutWorldContext,
    #[serde(rename = "apply_inheritance_nodes_without_server_context")]
    ApplyInheritanceNodesWithoutServerContext,
    #[serde(rename = "apply_inheritance_nodes_without_world_context")]
    ApplyInheritanceNodesWithoutWorldContext,
}

impl Default for Flags {
    fn default() -> Flags {
        Self::ResolveInheritance
    }
}

