/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SyncType : Represents the type of synchronisation task
/// Represents the type of synchronisation task
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SyncType {
    #[serde(rename = "full")]
    Full,
    #[serde(rename = "specific_user")]
    SpecificUser,

}

impl std::fmt::Display for SyncType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Full => write!(f, "full"),
            Self::SpecificUser => write!(f, "specific_user"),
        }
    }
}

impl Default for SyncType {
    fn default() -> SyncType {
        Self::Full
    }
}

