/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TemporaryNodeMergeStrategy : Controls how the implementation should behave when new temporary nodes are set that would otherwise conflict with existing entries.
/// Controls how the implementation should behave when new temporary nodes are set that would otherwise conflict with existing entries.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TemporaryNodeMergeStrategy {
    #[serde(rename = "add_new_duration_to_existing")]
    AddNewDurationToExisting,
    #[serde(rename = "replace_existing_if_duration_longer")]
    ReplaceExistingIfDurationLonger,
    #[serde(rename = "none")]
    None,

}

impl std::fmt::Display for TemporaryNodeMergeStrategy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AddNewDurationToExisting => write!(f, "add_new_duration_to_existing"),
            Self::ReplaceExistingIfDurationLonger => write!(f, "replace_existing_if_duration_longer"),
            Self::None => write!(f, "none"),
        }
    }
}

impl Default for TemporaryNodeMergeStrategy {
    fn default() -> TemporaryNodeMergeStrategy {
        Self::AddNewDurationToExisting
    }
}

