/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Track {
    /// A group name
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "groups")]
    pub groups: Vec<String>,
}

impl Track {
    pub fn new(name: String, groups: Vec<String>) -> Track {
        Track { name, groups }
    }
}
