/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TrackRequest : A request to promote or demote a user along a track.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrackRequest {
    #[serde(rename = "track")]
    pub track: String,
    /// A set of context pairs.
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<Vec<models::Context>>,
}

impl TrackRequest {
    /// A request to promote or demote a user along a track.
    pub fn new(track: String) -> TrackRequest {
        TrackRequest {
            track,
            context: None,
        }
    }
}

