/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    /// A player unique id (UUID)
    #[serde(rename = "uniqueId")]
    pub unique_id: uuid::Uuid,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "parentGroups", skip_serializing_if = "Option::is_none")]
    pub parent_groups: Option<Vec<String>>,
    /// A map (array) of nodes.
    #[serde(rename = "nodes")]
    pub nodes: Vec<models::Node>,
    #[serde(rename = "metadata")]
    pub metadata: Box<models::Metadata>,
}

impl User {
    pub fn new(unique_id: uuid::Uuid, nodes: Vec<models::Node>, metadata: models::Metadata) -> User {
        User {
            unique_id,
            username: None,
            parent_groups: None,
            nodes,
            metadata: Box::new(metadata),
        }
    }
}

